# -*- coding: utf-8 -*-
"""Week7_Data_Lake_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6Xx8lFPkXWeyL3Jg2PKZ-FZ57BGIdrw

## **Week-7 Assignment : Delta Lake MERGE Implementation Incremental Data Processing using Delta Lake (MERGE Operation)**

**Dataset:** Sample Superstore Dataset

**Author:** Snehal A. Bhosale

**College:** Sanjivani College of Engineering, Kopargaon – 423603

**E-mail:** snehalbhosale1807@gmail.com

**Technology Used:**  
Apache Spark (PySpark)  
Delta Lake  
Python  
Google Colab / Jupyter Notebook  
Spark SQL  
CSV File Format  
Delta Table

## **Objective:**

To understand Delta Lake fundamentals by implementing an incremental data processing pipeline using the MERGE operation. The assignment focuses on loading data into a Delta table, performing data cleaning, simulating incremental data, applying UPSERT (Update + Insert) using the MERGE command, validating the final dataset, and demonstrating the advantages of Delta Lake for reliable and efficient data management.

## **Assignment Implementation**

### **Step 1: Install Required Libraries**

Install PySpark and Delta Lake libraries required to create Delta tables and perform the MERGE operation.
"""

# Install Java and Delta Lake dependencies

!apt-get install -y openjdk-11-jdk-headless -qq > /dev/null
!pip install -q pyspark==3.5.1 delta-spark==3.2.0

import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"

"""### **Step 2: Import Required Libraries**

Import all the libraries required throughout the notebook.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from delta import configure_spark_with_delta_pip
from delta.tables import DeltaTable

"""### **Step 3: Initialize SparkSession with Delta Lake**

Create a Spark session and enable Delta Lake extensions.
"""

builder = (
    SparkSession.builder
    .appName("Delta Lake MERGE Assignment")
    .config("spark.sql.extensions",
            "io.delta.sql.DeltaSparkSessionExtension")
    .config("spark.sql.catalog.spark_catalog",
            "org.apache.spark.sql.delta.catalog.DeltaCatalog")
)

spark = configure_spark_with_delta_pip(builder).getOrCreate()

spark.sparkContext.setLogLevel("ERROR")

print("Spark Version :", spark.version)

"""### **Step 4: Upload and Load the Dataset**

Upload the Sample - Superstore.csv file from your local system and load it into a Spark DataFrame.
"""

from google.colab import files

# Upload the CSV file
uploaded = files.upload()


# Get the uploaded file name
file_name = list(uploaded.keys())[0]

# Read the uploaded CSV file into Spark
df = spark.read.csv(
    file_name,
    header=True,
    inferSchema=True
)

# Display first 5 records
df.show(5)

"""### **Step 6: Data Cleaning**

Remove duplicate records and handle missing values to prepare clean data for processing.
"""

print("Records Before Cleaning :", df.count())

df_clean = df.dropDuplicates()
df_clean = df_clean.dropna()

print("Records After Cleaning :", df_clean.count())

df_clean.show(5)

"""### **Step 7: Validate Cleaned Data**

Ensure that there are no duplicate Order IDs and no null values.
"""

print("Duplicate Order IDs")

df_clean.groupBy("Order ID") \
    .count() \
    .filter("count > 1") \
    .show()

print("Null Values")

df_clean.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in df_clean.columns
]).show()

"""### **Step 8: Create Master Dataset**

Use the first 80% of the cleaned dataset as the master dataset.
"""

from pyspark.sql.window import Window

# Add a unique row number to the cleaned DataFrame to ensure deterministic splitting
window_spec = Window.orderBy(monotonically_increasing_id())
df_with_row_num = df_clean.withColumn("row_num", row_number().over(window_spec))

total_rows = df_clean.count()
split_point = int(total_rows * 0.8)

master_df = df_with_row_num.filter(col("row_num") <= split_point).drop("row_num")

print("Master Dataset (first 5 records):")
master_df.show(5)

"""Save the master dataset."""

master_df.toPandas().to_csv(
    "customer_master.csv",
    index=False
)

"""Download the Cutomer_Master.csv"""

from google.colab import files

files.download("customer_master.csv")

"""### **Step 9: Create Incremental Dataset**

Create the remaining 20% of the records as the incremental dataset.
"""

from pyspark.sql.window import Window

# Re-add a unique row number to the cleaned DataFrame to ensure deterministic splitting
# This is necessary because df_clean might have been re-evaluated or lost its order
window_spec = Window.orderBy(monotonically_increasing_id())
df_with_row_num = df_clean.withColumn("row_num", row_number().over(window_spec))

total_rows = df_clean.count()
split_point = int(total_rows * 0.8)

incremental_df = df_with_row_num.filter(col("row_num") > split_point).drop("row_num")

print("Incremental Dataset (first 5 records):")
incremental_df.show(5)

"""Save the incremental dataset."""

incremental_df.toPandas().to_csv(
    "customer_incremental.csv",
    index=False
)

"""Download the Customer_Incremental.csv"""

from google.colab import files

files.download("customer_incremental.csv")

"""### **Step 10: Create Delta Table**

Load the master dataset into a Delta table.
"""

master = spark.read.csv(
    "customer_master.csv",
    header=True,
    inferSchema=True
)

# Rename columns to comply with Delta Lake naming conventions
master = master.withColumnRenamed("Row ID", "Row_ID") \
               .withColumnRenamed("Order ID", "Order_ID") \
               .withColumnRenamed("Order Date", "Order_Date") \
               .withColumnRenamed("Ship Date", "Ship_Date") \
               .withColumnRenamed("Ship Mode", "Ship_Mode") \
               .withColumnRenamed("Customer ID", "Customer_ID") \
               .withColumnRenamed("Customer Name", "Customer_Name") \
               .withColumnRenamed("Postal Code", "Postal_Code") \
               .withColumnRenamed("Product ID", "Product_ID") \
               .withColumnRenamed("Product Name", "Product_Name") \
               .withColumnRenamed("Sub-Category", "Sub_Category")

master.write \
    .format("delta") \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .save("delta/superstore")

"""Read the Delta table."""

spark.read \
    .format("delta") \
    .load("delta/superstore") \
    .show(5)

"""### **Step 11: Simulate Incremental Changes**

Modify a few existing records to simulate updates.
"""

incremental = spark.read.csv(
    "customer_incremental.csv",
    header=True,
    inferSchema=True
)

# Rename columns in incremental_df to match Delta table
incremental = incremental.withColumnRenamed("Row ID", "Row_ID") \
                           .withColumnRenamed("Order ID", "Order_ID") \
                           .withColumnRenamed("Order Date", "Order_Date") \
                           .withColumnRenamed("Ship Date", "Ship_Date") \
                           .withColumnRenamed("Ship Mode", "Ship_Mode") \
                           .withColumnRenamed("Customer ID", "Customer_ID") \
                           .withColumnRenamed("Customer Name", "Customer_Name") \
                           .withColumnRenamed("Postal Code", "Postal_Code") \
                           .withColumnRenamed("Product ID", "Product_ID") \
                           .withColumnRenamed("Product Name", "Product_Name") \
                           .withColumnRenamed("Sub-Category", "Sub_Category")

incremental = incremental.withColumn(
    "Sales",
    col("Sales") + 100
)

"""Create a few new records to simulate new incoming data."""

new_orders = spark.createDataFrame([
(99991, "CA-99991","2026-01-01","2026-01-04","Second Class","CG-100","John Smith","Consumer","United States","Los Angeles","California",90001,"West","OFF-PA-10009991","Office Supplies","Paper","Premium Paper",250.0,"5","0.10",50.0),

(99992, "CA-99992","2026-01-02","2026-01-05","Standard Class","CG-101","Emma Davis","Corporate","United States","Dallas","Texas",75001,"Central","TEC-PH-10009992","Technology","Phones","Smart Phone",850.0,"2","0.00",300.0),

(99993, "CA-99993","2026-01-03","2026-01-06","First Class","CG-102","David Wilson","Home Office","United States","Miami","Florida",33101,"South","FUR-CH-10009993","Furniture","Chairs","Office Chair",450.0,"3","0.15",90.0)
], incremental.schema)

"""Combine both datasets.

"""

incremental = incremental.union(new_orders)

incremental.show(5)

"""### **Step 12: Perform MERGE Operation**

Load the Delta table.
"""

delta_table = DeltaTable.forPath(
    spark,
    "delta/superstore"
)

"""Merge incremental records into the Delta table."""

delta_table.alias("target") \
.merge(
    incremental.alias("source"),
    "target.Row_ID = source.Row_ID"
) \
.whenMatchedUpdateAll() \
.whenNotMatchedInsertAll() \
.execute()

"""### **Step 13: Read Updated Delta Table**

Load the updated Delta table.
"""

final_df = spark.read \
    .format("delta") \
    .load("delta/superstore")

final_df.show(10)

"""### **Step 14: Validate Results**

Verify the final data after the MERGE operation.

Total Records
"""

print("Final Row Count :", final_df.count())

"""Duplicate Records"""

final_df.groupBy("Order_ID") \
    .count() \
    .filter("count > 1") \
    .show()

"""Null Values

"""

final_df.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in final_df.columns
]).show()

"""### **Step 15: Display Final Dataset**

Display the updated dataset and summary.
"""

print("Total Records :", final_df.count())

print("Unique Orders :",
      final_df.select("Order_ID").distinct().count())

print("Total Customers :",
      final_df.select("Customer_ID").distinct().count())

final_df.show(20, truncate=False)

"""### **SCD Type 1 vs SCD Type 2**

**SCD Type 1 (Slowly Changing Dimension Type 1)** handles changes by overwriting the existing data in the dimension table with the new data. This means no history of the changes is preserved; only the most current version of the record is available.

**SCD Type 2 (Slowly Changing Dimension Type 2)** preserves the full history of changes by adding new rows to the dimension table when a change occurs. It typically includes additional columns like `is_current`, `effective_date`, and `end_date` to track the validity period of each version of a record.

### **Step 16: Modify Delta Table Schema for SCD Type 2**

To implement SCD Type 2, we need to add three new columns to our Delta table: `is_current` (boolean), `effective_date` (timestamp), and `end_date` (timestamp, nullable). We will load the existing data, add these columns with initial values, and then overwrite the table using `overwriteSchema='true'` to update the schema.
"""

from pyspark.sql.functions import lit, current_timestamp, col

print("Updating Delta table schema for SCD Type 2...")

# Load the current Delta table
current_delta_df = spark.read.format("delta").load("delta/superstore")

# Add new SCD Type 2 columns if they don't already exist
if "is_current" not in current_delta_df.columns:
    current_delta_df = current_delta_df.withColumn("is_current", lit(True))
    print("  - Added 'is_current' column.")
if "effective_date" not in current_delta_df.columns:
    current_delta_df = current_delta_df.withColumn("effective_date", current_timestamp())
    print("  - Added 'effective_date' column.")
if "end_date" not in current_delta_df.columns:
    current_delta_df = current_delta_df.withColumn("end_date", lit(None).cast("timestamp"))
    print("  - Added 'end_date' column.")

# Overwrite the Delta table with the updated schema and initial values
current_delta_df.write \
    .format("delta") \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .save("delta/superstore")

print("Delta table schema updated for SCD Type 2.")
print("New schema of delta/superstore:")
spark.read.format("delta").load("delta/superstore").printSchema()

"""### **Step 17: Implement SCD Type 2 Merge**

Apply the **SCD Type 2** approach to maintain historical records by creating a new version whenever data changes.

* **Expire Existing Records:** Update matching active records with changed **Sales** values by setting is_current = false and end_date = current_timestamp().

* **Insert New Records:** Insert updated and new records as the latest version with is_current = true`, effective_date = current_timestamp(), and end_date = NULL.

This ensures complete data history while keeping only the latest record active.

"""

print("Preparing incremental data for SCD Type 2 merge...")

# Re-prepare the incremental data for SCD Type 2 merge
# Start with the original customer_incremental.csv
incremental_base_scd2 = spark.read.csv(
    "customer_incremental.csv",
    header=True,
    inferSchema=True
)

# Rename columns to match Delta table naming conventions
incremental_base_scd2 = incremental_base_scd2.withColumnRenamed("Row ID", "Row_ID") \
                                           .withColumnRenamed("Order ID", "Order_ID") \
                                           .withColumnRenamed("Order Date", "Order_Date") \
                                           .withColumnRenamed("Ship Date", "Ship_Date") \
                                           .withColumnRenamed("Ship Mode", "Ship_Mode") \
                                           .withColumnRenamed("Customer ID", "Customer_ID") \
                                           .withColumnRenamed("Customer Name", "Customer_Name") \
                                           .withColumnRenamed("Postal Code", "Postal_Code") \
                                           .withColumnRenamed("Product ID", "Product_ID") \
                                           .withColumnRenamed("Product Name", "Product_Name") \
                                           .withColumnRenamed("Sub-Category", "Sub_Category")

# Cast numeric columns to string to match the target Delta table schema
incremental_base_scd2 = incremental_base_scd2.withColumn("Sales", col("Sales").cast("string")) \
                                           .withColumn("Quantity", col("Quantity").cast("string")) \
                                           .withColumn("Discount", col("Discount").cast("string")) \
                                           .withColumn("Profit", col("Profit").cast("string"))

# Apply the sales update for existing incremental records
incremental_updates_scd2 = incremental_base_scd2.withColumn("Sales", (col("Sales").cast("double") + 100).cast("string"))

# Create new orders
new_orders_scd2 = spark.createDataFrame([
    (99991, "CA-99991","2026-01-01","2026-01-04","Second Class","CG-100","John Smith","Consumer","United States","Los Angeles","California",90001,"West","OFF-PA-10009991","Office Supplies","Paper","Premium Paper","250.0","5","0.10","50.0"),
    (99992, "CA-99992","2026-01-02","2026-01-05","Standard Class","CG-101","Emma Davis","Corporate","United States","Dallas","Texas",75001,"Central","TEC-PH-10009992","Technology","Phones","Smart Phone","850.0","2","0.00","300.0"),
    (99993, "CA-99993","2026-01-03","2026-01-06","First Class","CG-102","David Wilson","Home Office","United States","Miami","Florida",33101,"South","FUR-CH-10009993","Furniture","Chairs","Office Chair","450.0","3","0.15","90.0")
], incremental_base_scd2.schema) # Use the schema of incremental_base_scd2 after casting to string

# Combine updated existing records and new records
incremental_for_scd2 = incremental_updates_scd2.union(new_orders_scd2)

# Load the Delta table for the merge operation
delta_table = DeltaTable.forPath(spark, "delta/superstore")

print("Starting SCD Type 2 MERGE operation...")

# Step 1: Expire old rows for changed records
print("  - Expiring old versions of changed records...")
delta_table.alias("target") \
    .merge(
        incremental_for_scd2.alias("source"),
        "target.Row_ID = source.Row_ID AND target.is_current = true AND target.Sales != source.Sales"
    ) \
    .whenMatchedUpdate(set={ "is_current": lit(False), "end_date": current_timestamp() }) \
    .execute()
print("  - Old versions expired.")

# Step 2: Insert new records and new versions of updated records
print("  - Inserting new records and new versions of changed records...")
delta_table.alias("target") \
    .merge(
        incremental_for_scd2.alias("source"),
        "target.Row_ID = source.Row_ID AND target.is_current = true"
    ) \
    .whenNotMatchedInsert(values = {
        "Row_ID": "source.Row_ID",
        "Order_ID": "source.Order_ID",
        "Order_Date": "source.Order_Date",
        "Ship_Date": "source.Ship_Date",
        "Ship_Mode": "source.Ship_Mode",
        "Customer_ID": "source.Customer_ID",
        "Customer_Name": "source.Customer_Name",
        "Segment": "source.Segment",
        "Country": "source.Country",
        "City": "source.City",
        "State": "source.State",
        "Postal_Code": "source.Postal_Code",
        "Region": "source.Region",
        "Product_ID": "source.Product_ID",
        "Category": "source.Category",
        "Sub_Category": "source.Sub_Category",
        "Product_Name": "source.Product_Name",
        "Sales": "source.Sales",
        "Quantity": "source.Quantity",
        "Discount": "source.Discount",
        "Profit": "source.Profit",
        "is_current": "true",
        "effective_date": "current_timestamp()",
        "end_date": "null"
    }) \
    .execute()
print("  - New records and new versions inserted.")

print("SCD Type 2 MERGE operation completed.")

"""### **Step 18: Validate SCD2 Results**

Let's validate the SCD Type 2 implementation by querying a `Row_ID` that was part of the incremental update. We should see two versions of this record: one with `is_current = false` (the old version) and one with `is_current = true` (the new, updated version with higher sales).
"""

# Load the updated Delta table after SCD2 merge
final_df_scd2 = spark.read.format("delta").load("delta/superstore")

# Pick a Row_ID that was updated in the incremental step (e.g., Row_ID = 364 from customer_incremental.csv)
# Display both the expired and current versions for that Row_ID
print("SCD Type 2 validation for Row_ID = 364:")
final_df_scd2.filter(col("Row_ID") == 364).orderBy("effective_date").show(truncate=False)

"""### **Step 19: Delta Time Travel Demo**

Delta Lake's Time Travel feature allows us to query previous versions of a table. Let's demonstrate this by reading the table as it was at version 0 (before any merges) and comparing its row count to the current version.
"""

print("Demonstrating Delta Time Travel:")

# Read the Delta table at version 0 (initial state)
delta_version_0_df = spark.read.format("delta").option("versionAsOf", 0).load("delta/superstore")
print(f"Row count of Delta table at version 0: {delta_version_0_df.count()}")

# Read the current (latest) version of the Delta table
current_delta_df = spark.read.format("delta").load("delta/superstore")
print(f"Row count of current Delta table: {current_delta_df.count()}")

print("Time travel successful. The current version has more rows due to SCD Type 2 updates and inserts.")

"""### **Step 20: Display Delta Transaction Log / Audit History**

Delta Lake maintains a transaction log that records every operation performed on a Delta table. This log provides an audit trail and is essential for features like Time Travel. Let's examine the history of our `delta/superstore` table.
"""

print("Displaying Delta transaction log for 'delta/superstore':")
spark.sql("DESCRIBE HISTORY 'delta/superstore'").show(truncate=False)

"""### **Step 21: Idempotency Check for SCD Type 2 Merge**

An idempotent operation is one that can be applied multiple times without changing the result beyond the initial application. Let's re-run the exact same SCD Type 2 merge logic from Step 17 without introducing new incremental changes. We will check the count of current records before and after to demonstrate that re-running the merge does not create duplicate current versions or unintended side effects.
"""

print("Performing Idempotency Check for SCD Type 2 Merge...")

# Get the count of current records before re-running the merge
current_records_before_rerun = spark.read.format("delta").load("delta/superstore").filter(col("is_current") == True).count()
print(f"Count of current records before re-run: {current_records_before_rerun}")

# Re-run the exact same SCD Type 2 merge logic from Step 17
# (Using the previously prepared incremental_for_scd2 DataFrame)

print("  - Re-executing MERGE to expire old versions...")
delta_table.alias("target") \
    .merge(
        incremental_for_scd2.alias("source"),
        "target.Row_ID = source.Row_ID AND target.is_current = true AND target.Sales != source.Sales"
    ) \
    .whenMatchedUpdate(set={ "is_current": lit(False), "end_date": current_timestamp() }) \
    .execute()
print("  - Old versions expired.")

print("  - Re-executing MERGE to insert new records and versions...")
delta_table.alias("target") \
    .merge(
        incremental_for_scd2.alias("source"),
        "target.Row_ID = source.Row_ID AND target.is_current = true"
    ) \
    .whenNotMatchedInsert(values = {
        "Row_ID": "source.Row_ID",
        "Order_ID": "source.Order_ID",
        "Order_Date": "source.Order_Date",
        "Ship_Date": "source.Ship_Date",
        "Ship_Mode": "source.Ship_Mode",
        "Customer_ID": "source.Customer_ID",
        "Customer_Name": "source.Customer_Name",
        "Segment": "source.Segment",
        "Country": "source.Country",
        "City": "source.City",
        "State": "source.State",
        "Postal_Code": "source.Postal_Code",
        "Region": "source.Region",
        "Product_ID": "source.Product_ID",
        "Category": "source.Category",
        "Sub_Category": "source.Sub_Category",
        "Product_Name": "source.Product_Name",
        "Sales": "source.Sales",
        "Quantity": "source.Quantity",
        "Discount": "source.Discount",
        "Profit": "source.Profit",
        "is_current": "true",
        "effective_date": "current_timestamp()",
        "end_date": "null"
    }) \
    .execute()
print("  - New records and new versions inserted.")

# Get the count of current records after re-running the merge
current_records_after_rerun = spark.read.format("delta").load("delta/superstore").filter(col("is_current") == True).count()
print(f"Count of current records after re-run: {current_records_after_rerun}")

if current_records_before_rerun == current_records_after_rerun:
    print("Idempotency check passed: Current record count remained the same.")
else:
    print("Idempotency check failed: Current record count changed.")

"""## **Conclusion**

In this assignment, the Sample Superstore dataset was loaded into a Delta table and cleaned by removing duplicate and null records. A fixed master and incremental dataset were created to keep the workflow reproducible. Using Delta Lake's MERGE operation, an SCD Type 1 upsert was first performed to update existing records and insert new ones. This was then extended to SCD Type 2, where changed records were preserved as historical versions instead of being overwritten, giving a full change history. Delta Lake's time travel feature and transaction history (DESCRIBE HISTORY) were used to verify past table states, and an idempotency check confirmed that re-running the merge did not create duplicate records. Overall, this implementation demonstrates a complete, reliable, and production-style incremental data pipeline using Delta Lake.
"""